#pragma once
#define SCREEN_WIDTH 512
#define SCREEN_HEIGHT 416
#define MOVEMENTSPEED 50.0f
#define JUMP_FORCE_DECREMENT 350.0f
#define MARIO_HEIGHT 64
#define GRAVITY 300.0f
#define INITIAL_JUMP_FORCE 600.0f
#define MAP_HEIGHT 13
#define MAP_WIDTH 16
#define TILE_HEIGHT 32
#define TILE_WIDTH 32
#define SHAKE_DURATION 1
#define KOOPA_DAMAGE_TIME 3.0f
#define INITIAL_JUMP_FORCE_SMALL 200.0f
#define CHARACTER_START_HEIGHT 330;
#define LUIGI_START
#define MARIO_START
#define KOOPA_SPEED 96.0f